import "./style.scss"
import "./header/header.scss"
import "../node_modules/jquery/dist/jquery.min.js"
import "./fonts/webpack-icons-installer/node_modules/font-awesome/scss/font-awesome.scss"
import "./fonts/fonts.scss"
import "./content/slider/slider.scss"
import "./content/slider/slider.js"
// import "./plugins/owl-carusel/js/owl.carousel.js"
// import "./plugins/owl-carusel/scss/owl.scss"
// import "./plugins/owl-carusel/scss/owl.theme.default.scss"
import "./plugins/slick/slick.scss"
import "./plugins/slick/slick.js"